/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.presentacion_mariscos.mermas;

import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import com.mycompany.controller_mariscos.insumo.IInsumoControl;
import com.mycompany.controller_mariscos.insumo.InsumoControl;
import com.mycompany.controller_mariscos.inventario.IInventarioControl;
import com.mycompany.controller_mariscos.inventario.InventarioControl;
import com.mycompany.controller_mariscos.merma.IMermaControl;
import com.mycompany.controller_mariscos.merma.MermaControl;
import com.mycompany.dto_mariscos.Insumo;
import com.mycompany.dto_mariscos.Inventario;
import com.mycompany.dto_mariscos.mermas.MermaDTO;
import com.mycompany.persistencia_mariscos.insumo.IInsumoDAO;
import com.mycompany.persistencia_mariscos.insumo.InsumoDAO;
import com.mycompany.persistencia_mariscos.inventario.IInventarioDAO;
import com.mycompany.persistencia_mariscos.inventario.InventarioDAO;
import com.mycompany.presentacion_mariscos.NavegadorUI;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;

import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author demib
 */
public class PnlRegistroMermas extends javax.swing.JPanel {
    
    
    //DAO Y CONTROLLER
    private IMermaControl mermaControl;
   
    
    private IInventarioControl inventarioControl;
    
    
    private IInsumoControl insumoControl;
    
    //Lista inventario
    private List<Inventario> listaInventario;
    
    
    
    
    

    /**
     * Creates new form pnlTablaMermas
     */
    public PnlRegistroMermas(IMermaControl mermaControl, IInventarioControl inventarioControl, IInsumoControl insumoControl) {
        this.mermaControl = mermaControl;
        this.inventarioControl = inventarioControl;
        this.insumoControl = insumoControl;
        
        
        
        
        initComponents();
        
        configurarTabla();
        cargarInsumos();
        
        ((javax.swing.text.AbstractDocument) txtCantPerdida.getDocument()).setDocumentFilter(new MyDecimalFilter());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTablaMermas = new javax.swing.JLabel();
        lblTablaLeyend = new javax.swing.JLabel();
        pnlInformacion = new javax.swing.JPanel();
        lblInformacion = new javax.swing.JLabel();
        pnlDatosInfo = new javax.swing.JPanel();
        lblInsumo = new javax.swing.JLabel();
        lblCantPerdida = new javax.swing.JLabel();
        lblUnidadMedida = new javax.swing.JLabel();
        txtInsumo = new javax.swing.JTextField();
        txtCantPerdida = new javax.swing.JTextField();
        txtUnidadMedida = new javax.swing.JTextField();
        lblCausaMerma = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblFecha = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        comboCausa = new javax.swing.JComboBox<>();
        chooserFecha = new com.toedter.calendar.JDateChooser();
        comboUbicacion = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInsumos = new javax.swing.JTable();
        btnRegistrarMerma = new javax.swing.JButton();
        lblPagina = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnSeleccionarQR = new javax.swing.JButton();
        barraBusqueda = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTablaMermas.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTablaMermas.setForeground(new java.awt.Color(0, 0, 0));
        lblTablaMermas.setText("Tabla de Insumos");

        lblTablaLeyend.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTablaLeyend.setForeground(new java.awt.Color(0, 0, 0));
        lblTablaLeyend.setText("Seleccione el insumo en la tabla o mediante QR y rellene los campos restantes para registrar la merma.");

        pnlInformacion.setBackground(new java.awt.Color(255, 255, 255));

        lblInformacion.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblInformacion.setForeground(new java.awt.Color(0, 0, 0));
        lblInformacion.setText("Informacion");

        pnlDatosInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlDatosInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblInsumo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblInsumo.setForeground(new java.awt.Color(0, 0, 0));
        lblInsumo.setText("Insumo");

        lblCantPerdida.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCantPerdida.setForeground(new java.awt.Color(0, 0, 0));
        lblCantPerdida.setText("Cantidad Perdida (kg, gr, pzs)");

        lblUnidadMedida.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblUnidadMedida.setForeground(new java.awt.Color(0, 0, 0));
        lblUnidadMedida.setText("Unidad de Medida");

        txtInsumo.setBackground(new java.awt.Color(204, 204, 204));
        txtInsumo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtInsumo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtInsumo.setFocusable(false);

        txtCantPerdida.setBackground(new java.awt.Color(255, 255, 255));
        txtCantPerdida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtUnidadMedida.setBackground(new java.awt.Color(204, 204, 204));
        txtUnidadMedida.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtUnidadMedida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtUnidadMedida.setFocusable(false);

        lblCausaMerma.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCausaMerma.setForeground(new java.awt.Color(0, 0, 0));
        lblCausaMerma.setText("Causa de Merma");

        lblDescripcion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion.setText("Descripcion");

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(txtDescripcion);

        lblFecha.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha");

        lblUbicacion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        lblUbicacion.setText("Ubicacion");

        comboCausa.setBackground(new java.awt.Color(255, 255, 255));
        comboCausa.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        comboCausa.setForeground(new java.awt.Color(0, 0, 0));
        comboCausa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caducidad / Descomposicion", "Mal estado al recibir", "Error de Preparacion", "Accidente / Caida", "Mala Conservacion", "Sobreproduccion", "Robo / Perdida" }));

        chooserFecha.setBackground(new java.awt.Color(255, 255, 255));

        comboUbicacion.setBackground(new java.awt.Color(255, 255, 255));
        comboUbicacion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        comboUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        comboUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almacen / Bodega", "Camara de Congelacion / Refris", "Area de Preparacion ( Cocina )", "Barra de Bebidas", "Comedor / Servicio", "Transporte / Recepcion" }));

        javax.swing.GroupLayout pnlDatosInfoLayout = new javax.swing.GroupLayout(pnlDatosInfo);
        pnlDatosInfo.setLayout(pnlDatosInfoLayout);
        pnlDatosInfoLayout.setHorizontalGroup(
            pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboCausa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInsumo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantPerdida, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUnidadMedida, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInsumo, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(txtCantPerdida, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(txtUnidadMedida, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(lblCausaMerma, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFecha)
                    .addComponent(lblUbicacion)
                    .addComponent(chooserFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboUbicacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDatosInfoLayout.setVerticalGroup(
            pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsumo)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtInsumo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(chooserFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantPerdida)
                    .addComponent(lblUbicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboUbicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUnidadMedida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCausaMerma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCausa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlInformacionLayout = new javax.swing.GroupLayout(pnlInformacion);
        pnlInformacion.setLayout(pnlInformacionLayout);
        pnlInformacionLayout.setHorizontalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblInformacion)
                    .addComponent(pnlDatosInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInformacionLayout.setVerticalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(pnlDatosInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblInsumos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblInsumos.setSelectionBackground(new java.awt.Color(35, 52, 75));
        tblInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInsumosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblInsumos);

        btnRegistrarMerma.setBackground(new java.awt.Color(35, 52, 75));
        btnRegistrarMerma.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnRegistrarMerma.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarMerma.setText("Registrar Merma");
        btnRegistrarMerma.setBorderPainted(false);
        btnRegistrarMerma.setFocusPainted(false);
        btnRegistrarMerma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMermaActionPerformed(evt);
            }
        });

        lblPagina.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblPagina.setForeground(new java.awt.Color(0, 0, 0));
        lblPagina.setText("jLabel1");

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnSeleccionarQR.setBackground(new java.awt.Color(35, 52, 75));
        btnSeleccionarQR.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnSeleccionarQR.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarQR.setText("Seleccionar por QR");
        btnSeleccionarQR.setBorderPainted(false);
        btnSeleccionarQR.setFocusPainted(false);
        btnSeleccionarQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarQRActionPerformed(evt);
            }
        });

        barraBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        barraBusqueda.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        barraBusqueda.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTablaLeyend)
                            .addComponent(lblTablaMermas))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSeleccionarQR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPagina)
                                .addGap(18, 18, 18)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(barraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 91, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlInformacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRegistrarMerma)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTablaMermas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTablaLeyend)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(barraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarMerma, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnterior)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSiguiente)
                                .addComponent(lblPagina)))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSeleccionarQR)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMermaActionPerformed
        try{
            
            String nombre = txtInsumo.getText();
            
//            Insumo insumo = insumoControl.obtenerInsumoPorNombre(nombre);
//            String id = insumo.getId().toHexString();
            
            double cantPerdida = Double.parseDouble(txtCantPerdida.getText());
            String unidadMedida = txtUnidadMedida.getText();
            String causaMerma = comboCausa.getSelectedItem().toString();
            String descripcion = txtDescripcion.getText();
            
            //Obtener fecha tipo date por JCalendar
            Date fecha = chooserFecha.getDate();
            
            // validar fecha
            if (chooserFecha.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Seleccione una fecha");
                return;
            }
        
            //Convertir Date a LocalDateTime
            LocalDateTime fechaLocal = fecha.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDateTime();
            
            String ubicacion = comboUbicacion.getSelectedItem().toString();
            
            MermaDTO mermaDTO = new MermaDTO(null, nombre, cantPerdida, unidadMedida, causaMerma, descripcion, ubicacion, fechaLocal);
            
            mermaControl.crearMerma(mermaDTO);
            JOptionPane.showMessageDialog(this, "Merma registrada correctamente!");

                    
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al registrar merma: " + e.getMessage());

        }
        
    }//GEN-LAST:event_btnRegistrarMermaActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        int totalPaginas = (int) Math.ceil((double) listaInventario.size() / REGISTROS_POR_PAGINA);
        if (paginaActual < totalPaginas - 1) {
            paginaActual++;
            cargarPagina(paginaActual);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (paginaActual > 0) {
            paginaActual--;
            cargarPagina(paginaActual);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSeleccionarQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarQRActionPerformed
        // TODO add your handling code here:
        //Le pasamos la carpeta al filechooser para que este al dar clic en el boton se abra justo en la carpeta
        File carpetaQR = new File("qrs");
        JFileChooser fileChooser = new JFileChooser(carpetaQR);
        
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imagenes", "png", "jpg"));

        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            leerQR(archivo);
        }
    }//GEN-LAST:event_btnSeleccionarQRActionPerformed

    private void tblInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInsumosMouseClicked
        // TODO add your handling code here:
        int fila = tblInsumos.getSelectedRow();
        if (fila >= 0) {
            int indiceReal = paginaActual * REGISTROS_POR_PAGINA + fila;
            Inventario inventario = listaInventario.get(indiceReal); // ✅
            txtInsumo.setText(inventario.getInsumo().getNombre());
            txtUnidadMedida.setText(inventario.getInsumo().getUnidadMedida());
        }
    }//GEN-LAST:event_tblInsumosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraBusqueda;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnRegistrarMerma;
    private javax.swing.JButton btnSeleccionarQR;
    private javax.swing.JButton btnSiguiente;
    private com.toedter.calendar.JDateChooser chooserFecha;
    private javax.swing.JComboBox<String> comboCausa;
    private javax.swing.JComboBox<String> comboUbicacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantPerdida;
    private javax.swing.JLabel lblCausaMerma;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblInsumo;
    private javax.swing.JLabel lblPagina;
    private javax.swing.JLabel lblTablaLeyend;
    private javax.swing.JLabel lblTablaMermas;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblUnidadMedida;
    private javax.swing.JPanel pnlDatosInfo;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JTable tblInsumos;
    private javax.swing.JTextField txtCantPerdida;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtInsumo;
    private javax.swing.JTextField txtUnidadMedida;
    // End of variables declaration//GEN-END:variables

    private void configurarTabla(){
        String[] columnas ={"Insumo", "Stock", "Categoria"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // nadie puede editar las celdas
            }
        };
        
        tblInsumos.setModel(modelo);
    }
    
    private int paginaActual = 0;
    private final int REGISTROS_POR_PAGINA = 5;

    private void cargarInsumos() {
        try {
            listaInventario = inventarioControl.obtenerTodos();
            cargarPagina(paginaActual);

            // Clic en fila para rellenar los campos
            tblInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    int fila = tblInsumos.getSelectedRow();
                    if (fila >= 0) {
                        // Calcular índice real segun pagina actual
                        int indiceReal = paginaActual * REGISTROS_POR_PAGINA + fila;
                        Inventario inventario = listaInventario.get(indiceReal);

                        txtInsumo.setText(inventario.getInsumo().getNombre());
                        txtUnidadMedida.setText(inventario.getInsumo().getUnidadMedida());
                    }
                }
            });

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar insumos: " + e.getMessage());
        }
    }

    private void cargarPagina(int pagina) {
        DefaultTableModel modelo = (DefaultTableModel) tblInsumos.getModel();
        modelo.setRowCount(0);

        int inicio = pagina * REGISTROS_POR_PAGINA;
        int fin = Math.min(inicio + REGISTROS_POR_PAGINA, listaInventario.size());

        for (int i = inicio; i < fin; i++) {
            Inventario inv = listaInventario.get(i);
            modelo.addRow(new Object[]{
                inv.getInsumo().getNombre(),
                inv.getStockActual(),
                inv.getInsumo().getCategoria()
            });
        }

        int totalPaginas = (int) Math.ceil((double) listaInventario.size() / REGISTROS_POR_PAGINA);
        lblPagina.setText("Página " + (pagina + 1) + " de " + totalPaginas);
    }
    
    private void leerQR(File archivo) {
        try {
            BufferedImage imagen = ImageIO.read(archivo);
            LuminanceSource source = new BufferedImageLuminanceSource(imagen);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

            Result result = new MultiFormatReader().decode(bitmap);
            String contenidoQR = result.getText(); // el nombre del insumo puesto en el metodo generarQR

            // buscar el insumo por el contenido del QR
            Insumo insumo = insumoControl.obtenerInsumoPorNombre(contenidoQR);

            // rellenar campos
            txtInsumo.setText(insumo.getNombre());
            txtUnidadMedida.setText(insumo.getUnidadMedida());

        } catch (NotFoundException e) {
            JOptionPane.showMessageDialog(this, "No se encontro ningun QR en la imagen");
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, "Error al leer QR: " + e.getMessage());
        }
    }
    
    //Filtro para txtCantPerdida para que solo acepte numeros enteros y decimales
    class MyDecimalFilter extends javax.swing.text.DocumentFilter {
        private static final String REGEX = "^[0-9]*\\.?[0-9]*$";

        @Override
        public void insertString(FilterBypass fb, int offset, String string, javax.swing.text.AttributeSet attr) 
                throws javax.swing.text.BadLocationException {
            String currentText = fb.getDocument().getText(0, fb.getDocument().getLength());
            String nextText = currentText.substring(0, offset) + string + currentText.substring(offset);
            if (nextText.matches(REGEX)) { super.insertString(fb, offset, string, attr); }
        }

        @Override
        public void replace(FilterBypass fb, int offset, int length, String text, javax.swing.text.AttributeSet attrs) 
                throws javax.swing.text.BadLocationException {
            String currentText = fb.getDocument().getText(0, fb.getDocument().getLength());
            String nextText = currentText.substring(0, offset) + text + currentText.substring(offset + length);
            if (nextText.matches(REGEX)) { super.replace(fb, offset, length, text, attrs); }
        }
    }

    
}
