/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.presentacion_mariscos.mermas;

import com.mycompany.controller_mariscos.insumo.IInsumoControl;
import com.mycompany.controller_mariscos.inventario.IInventarioControl;
import com.mycompany.controller_mariscos.merma.IMermaControl;
import com.mycompany.controller_mariscos.merma.MermaControl;
import com.mycompany.dto_mariscos.mermas.MermaDTO;
import com.mycompany.presentacion_mariscos.NavegadorUI;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author demib
 */
public class PnlTablaMermas extends javax.swing.JPanel {
    
    
    //Controller
    private IMermaControl mermaControl;
    private IInventarioControl inventarioControl;
    private IInsumoControl insumoControl;
    //Lista Mermas
    private List<MermaDTO> listaMermas;
    
    //Panel de Registro de Mermas
    PnlRegistroMermas pnlRegistroMermas;
    

    /**
     * Creates new form pnlTablaMermas
     */
    public PnlTablaMermas(IMermaControl mermaControl, IInventarioControl inventarioControl, IInsumoControl insumoControl) {
        this.mermaControl = mermaControl;
        this.inventarioControl = inventarioControl;
        this.insumoControl = insumoControl;
        initComponents();
        
        
        pnlRegistroMermas = new PnlRegistroMermas(mermaControl, inventarioControl, insumoControl);
        
        configurarTabla();
        cargarMermas();
        barraBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtrarMermas(barraBusqueda.getText());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTablaMermas = new javax.swing.JLabel();
        lblTablaLeyend = new javax.swing.JLabel();
        pnlInformacion = new javax.swing.JPanel();
        lblInformacion = new javax.swing.JLabel();
        pnlDatosInfo = new javax.swing.JPanel();
        lblInsumo = new javax.swing.JLabel();
        lblCantPerdida = new javax.swing.JLabel();
        lblUnidadMedida = new javax.swing.JLabel();
        txtInsumo = new javax.swing.JTextField();
        txtCantPerdida = new javax.swing.JTextField();
        txtUnidadMedida = new javax.swing.JTextField();
        lblCausaMerma = new javax.swing.JLabel();
        txtCausa = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblFecha = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMermas = new javax.swing.JTable();
        btnCrearMerma = new javax.swing.JButton();
        lblTablaLeyend1 = new javax.swing.JLabel();
        barraBusqueda = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTablaMermas.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTablaMermas.setForeground(new java.awt.Color(0, 0, 0));
        lblTablaMermas.setText("Tabla de Mermas");

        lblTablaLeyend.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTablaLeyend.setForeground(new java.awt.Color(0, 0, 0));
        lblTablaLeyend.setText("Seleccione la merma en la tabla para ver los detalles.");

        pnlInformacion.setBackground(new java.awt.Color(255, 255, 255));

        lblInformacion.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblInformacion.setForeground(new java.awt.Color(0, 0, 0));
        lblInformacion.setText("Informacion");

        pnlDatosInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlDatosInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblInsumo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblInsumo.setForeground(new java.awt.Color(0, 0, 0));
        lblInsumo.setText("Insumo");

        lblCantPerdida.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCantPerdida.setForeground(new java.awt.Color(0, 0, 0));
        lblCantPerdida.setText("Cantidad Perdida (kg, gr, pzs)");

        lblUnidadMedida.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblUnidadMedida.setForeground(new java.awt.Color(0, 0, 0));
        lblUnidadMedida.setText("Unidad de Medida");

        txtInsumo.setBackground(new java.awt.Color(204, 204, 204));
        txtInsumo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtInsumo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtInsumo.setFocusable(false);

        txtCantPerdida.setBackground(new java.awt.Color(204, 204, 204));
        txtCantPerdida.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtCantPerdida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCantPerdida.setFocusable(false);

        txtUnidadMedida.setBackground(new java.awt.Color(204, 204, 204));
        txtUnidadMedida.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtUnidadMedida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtUnidadMedida.setFocusable(false);

        lblCausaMerma.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCausaMerma.setForeground(new java.awt.Color(0, 0, 0));
        lblCausaMerma.setText("Causa de Merma");

        txtCausa.setBackground(new java.awt.Color(204, 204, 204));
        txtCausa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtCausa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCausa.setFocusable(false);

        lblDescripcion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion.setText("Descripcion");

        txtDescripcion.setBackground(new java.awt.Color(204, 204, 204));
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDescripcion.setEnabled(false);
        jScrollPane1.setViewportView(txtDescripcion);

        lblFecha.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha");

        lblUbicacion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        lblUbicacion.setText("Ubicacion");

        txtUbicacion.setBackground(new java.awt.Color(204, 204, 204));
        txtUbicacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtUbicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtUbicacion.setFocusable(false);

        txtFecha.setBackground(new java.awt.Color(204, 204, 204));
        txtFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        txtFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtFecha.setFocusable(false);
        txtFecha.setOpaque(true);

        javax.swing.GroupLayout pnlDatosInfoLayout = new javax.swing.GroupLayout(pnlDatosInfo);
        pnlDatosInfo.setLayout(pnlDatosInfoLayout);
        pnlDatosInfoLayout.setHorizontalGroup(
            pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsumo)
                    .addComponent(lblCantPerdida)
                    .addComponent(lblUnidadMedida)
                    .addComponent(txtInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCausaMerma)
                    .addComponent(lblDescripcion)
                    .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                        .addComponent(txtCausa, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFecha)
                        .addComponent(lblUbicacion)
                        .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlDatosInfoLayout.setVerticalGroup(
            pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsumo)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantPerdida)
                    .addComponent(lblUbicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblUnidadMedida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCausaMerma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCausa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlInformacionLayout = new javax.swing.GroupLayout(pnlInformacion);
        pnlInformacion.setLayout(pnlInformacionLayout);
        pnlInformacionLayout.setHorizontalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblInformacion)
                    .addComponent(pnlDatosInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInformacionLayout.setVerticalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInformacion)
                .addGap(18, 18, 18)
                .addComponent(pnlDatosInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblMermas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblMermas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblMermas);

        btnCrearMerma.setBackground(new java.awt.Color(35, 52, 75));
        btnCrearMerma.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnCrearMerma.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearMerma.setText("Crear Merma");
        btnCrearMerma.setBorderPainted(false);
        btnCrearMerma.setFocusPainted(false);
        btnCrearMerma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMermaActionPerformed(evt);
            }
        });

        lblTablaLeyend1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTablaLeyend1.setForeground(new java.awt.Color(0, 0, 0));
        lblTablaLeyend1.setText("Para registrar una merma presione el boton Crear Merma.");

        barraBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        barraBusqueda.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        barraBusqueda.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTablaLeyend)
                            .addComponent(lblTablaMermas))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTablaLeyend1)
                            .addComponent(barraBusqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(pnlInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearMerma)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTablaMermas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTablaLeyend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTablaLeyend1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearMerma, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMermaActionPerformed
        NavegadorUI.navegar(pnlRegistroMermas, "Registro Mermas");
    }//GEN-LAST:event_btnCrearMermaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraBusqueda;
    private javax.swing.JButton btnCrearMerma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantPerdida;
    private javax.swing.JLabel lblCausaMerma;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblInsumo;
    private javax.swing.JLabel lblTablaLeyend;
    private javax.swing.JLabel lblTablaLeyend1;
    private javax.swing.JLabel lblTablaMermas;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblUnidadMedida;
    private javax.swing.JPanel pnlDatosInfo;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JTable tblMermas;
    private javax.swing.JTextField txtCantPerdida;
    private javax.swing.JTextField txtCausa;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtInsumo;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txtUnidadMedida;
    // End of variables declaration//GEN-END:variables

    private void configurarTabla(){
        String[] columnas ={"Insumo", "Cantidad", "U. Medida", "Causa", "Fecha"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // nadie puede editar las celdas
            }
        };
        
        tblMermas.setModel(modelo);
    }
    
    private void cargarMermas(){
        try {
            listaMermas = mermaControl.obtenerTodos();
            DefaultTableModel modelo = (DefaultTableModel) tblMermas.getModel();
            modelo.setRowCount(0); // limpia filas anteriores

            for (MermaDTO m : listaMermas) {
                // formatea la fecha
                String fecha = m.getFechaOcurrido()
                    .atZone(java.time.ZoneId.systemDefault())
                    .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));

                modelo.addRow(new Object[]{
                    m.getNombreInsumo(),
                    m.getCantPerdida(),
                    m.getUnidadMedida(),
                    m.getCausa(),
                    fecha
                });
            }
            
            // Clic en fila para rellenar los campos de la derecha
            tblMermas.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    int fila = tblMermas.getSelectedRow();
                    if (fila >= 0) {
                        MermaDTO merma = listaMermas.get(fila);

                        String fecha = merma.getFechaOcurrido()
                            .atZone(java.time.ZoneId.systemDefault())
                            .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));

                        txtInsumo.setText(merma.getNombreInsumo());
                        txtCantPerdida.setText(String.valueOf(merma.getCantPerdida()));
                        txtUnidadMedida.setText(merma.getUnidadMedida());
                        txtCausa.setText(merma.getCausa());
                        txtUbicacion.setText(merma.getUbicacion());
                        txtFecha.setText(fecha);
                        txtDescripcion.setText(merma.getDescripcion());
                    }
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar mermas: " + e.getMessage());
        }
    }
    
    private void filtrarMermas(String textoBusqueda) {
        DefaultTableModel modelo = (DefaultTableModel) tblMermas.getModel();
        modelo.setRowCount(0);

        List<MermaDTO> filtradas;

        if (textoBusqueda == null || textoBusqueda.isBlank()) {
            filtradas = listaMermas;
        } else {
            filtradas = listaMermas.stream()
                .filter(m -> m.getNombreInsumo()
                    .toLowerCase()
                    .contains(textoBusqueda.toLowerCase()))
                .collect(java.util.stream.Collectors.toList());
        }

        for (MermaDTO m : filtradas) {
            String fecha = m.getFechaOcurrido()
                .atZone(java.time.ZoneId.systemDefault())
                .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));

            modelo.addRow(new Object[]{
                m.getNombreInsumo(),
                m.getCantPerdida(),
                m.getUnidadMedida(),
                m.getCausa(),
                fecha
            });
        }
    }
}
