/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.presentacion_mariscos.SolicitudFactura;

import com.mycompany.controller_mariscos.solicitudFactura.ISolicitudFacturaControl;
import com.mycompany.dto_mariscos.SolicitudFacturaDTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author 52644
 */
public class pnlDatosFacturacion extends javax.swing.JPanel {

    private ISolicitudFacturaControl solicitudControl;
    private SolicitudFacturaDTO solicitudFacturaDTO;
    private pnlConfirmacionFactura pnlConfirmacion;


    public pnlDatosFacturacion() {
        initComponents();
        inicializarComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        lblRazonSocial = new javax.swing.JLabel();
        lblCFDI = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblCodigoPostal = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCalle = new javax.swing.JLabel();
        rfcTextField = new javax.swing.JTextField();
        TextFieldrazonSocial = new javax.swing.JTextField();
        calleTextField = new javax.swing.JTextField();
        ciudadTextField = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        codigoPostalTextField = new javax.swing.JTextField();
        correoTextField = new javax.swing.JTextField();
        BtnLimpiarEspacios = new javax.swing.JButton();
        pnlDatosPedido = new javax.swing.JPanel();
        lblDatosPedido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosPedidoTextArea = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        cfdiComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1331, 772));

        lblTitulo.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Ingrese los Datos");

        lblRfc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRfc.setForeground(new java.awt.Color(0, 0, 0));
        lblRfc.setText("RFC: ");

        lblRazonSocial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRazonSocial.setForeground(new java.awt.Color(0, 0, 0));
        lblRazonSocial.setText("Razón social:");

        lblCFDI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCFDI.setForeground(new java.awt.Color(0, 0, 0));
        lblCFDI.setText("Uso de  CFDI:");

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccion.setText("Direccion:");

        lblCodigoPostal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigoPostal.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigoPostal.setText("Codigo Postal:");

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreo.setText("Correo: ");

        lblCalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCalle.setForeground(new java.awt.Color(0, 0, 0));
        lblCalle.setText("Calle:");

        rfcTextField.setForeground(new java.awt.Color(255, 255, 255));
        rfcTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfcTextFieldActionPerformed(evt);
            }
        });

        ciudadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadTextFieldActionPerformed(evt);
            }
        });

        lblCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCiudad.setForeground(new java.awt.Color(0, 0, 0));
        lblCiudad.setText("Ciudad:");

        BtnLimpiarEspacios.setBackground(new java.awt.Color(35, 53, 74));
        BtnLimpiarEspacios.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        BtnLimpiarEspacios.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiarEspacios.setText("Limpiar Espacios");
        BtnLimpiarEspacios.setToolTipText("");
        BtnLimpiarEspacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarEspaciosActionPerformed(evt);
            }
        });

        pnlDatosPedido.setBackground(new java.awt.Color(248, 248, 248));

        lblDatosPedido.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDatosPedido.setForeground(new java.awt.Color(0, 0, 0));
        lblDatosPedido.setText("Datos del Pedido:\n\n");

        datosPedidoTextArea.setBackground(new java.awt.Color(255, 255, 255));
        datosPedidoTextArea.setColumns(20);
        datosPedidoTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datosPedidoTextArea.setForeground(new java.awt.Color(0, 0, 0));
        datosPedidoTextArea.setRows(5);
        datosPedidoTextArea.setText("N°  de Pedido:  214.\n\nProveedor: pescadería Mar de cortes.\n\nCantidad: 15,265.00 MXN.\n\nFecha de pago:  30 - 03- 2026.");
        jScrollPane1.setViewportView(datosPedidoTextArea);

        javax.swing.GroupLayout pnlDatosPedidoLayout = new javax.swing.GroupLayout(pnlDatosPedido);
        pnlDatosPedido.setLayout(pnlDatosPedidoLayout);
        pnlDatosPedidoLayout.setHorizontalGroup(
            pnlDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPedidoLayout.createSequentialGroup()
                .addGroup(pnlDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosPedidoLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lblDatosPedido))
                    .addGroup(pnlDatosPedidoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlDatosPedidoLayout.setVerticalGroup(
            pnlDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPedidoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblDatosPedido)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnEnviar.setBackground(new java.awt.Color(35, 53, 74));
        btnEnviar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar >");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(35, 53, 74));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("< Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        cfdiComboBox.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cfdiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adquisición de mercancías", "Devoluciones", "descuentos o bonificaciones", "Gastos en general", "Construcciones", "Equipo de transporte", "Equipo de cómputo" }));
        cfdiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfdiComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(correoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoPostalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCorreo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigoPostal)
                        .addContainerGap(1204, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCalle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCiudad)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ciudadTextField))
                        .addGap(921, 921, 921))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldrazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addComponent(cfdiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRfc)
                                    .addComponent(lblTitulo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rfcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(BtnLimpiarEspacios))
                                    .addComponent(lblDireccion)
                                    .addComponent(lblCFDI)
                                    .addComponent(lblRazonSocial))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(113, 113, 113)
                        .addComponent(pnlDatosPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitulo)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRfc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rfcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnLimpiarEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRazonSocial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldrazonSocial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCFDI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cfdiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDatosPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCalle)
                            .addComponent(lblCiudad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ciudadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCodigoPostal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoPostalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(correoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(329, 329, 329))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ciudadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadTextFieldActionPerformed

    private void rfcTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfcTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfcTextFieldActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
    if (!validarCampos()) {
        return;
    }
 

    solicitudFacturaDTO.setRfc(rfcTextField.getText());
    solicitudFacturaDTO.setRazonSocial(TextFieldrazonSocial.getText());
    solicitudFacturaDTO.setUsoCFDI((String) cfdiComboBox.getSelectedItem());
    solicitudFacturaDTO.setCalle(calleTextField.getText());
    solicitudFacturaDTO.setCodigoPostal(codigoPostalTextField.getText());
    solicitudFacturaDTO.setCorreo(correoTextField.getText());
 
    pnlConfirmacion = new pnlConfirmacionFactura();
    pnlConfirmacion.setSolicitudDTO(solicitudFacturaDTO);

 
    JDialog dialogo = new JDialog();
    dialogo.setModal(true);
    dialogo.setTitle("Confirmación");
    dialogo.add(pnlConfirmacion);
    dialogo.setPreferredSize(new Dimension(600, 400));
    dialogo.pack();
    dialogo.setLocationRelativeTo(this);
    dialogo.setUndecorated(true);
    dialogo.setVisible(true);

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void BtnLimpiarEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarEspaciosActionPerformed
        rfcTextField.setText("");
        TextFieldrazonSocial.setText("");
        calleTextField.setText("");
        ciudadTextField.setText("");
        codigoPostalTextField.setText("");
        correoTextField.setText("");

    }//GEN-LAST:event_BtnLimpiarEspaciosActionPerformed

    private void cfdiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfdiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cfdiComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpiarEspacios;
    private javax.swing.JTextField TextFieldrazonSocial;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField calleTextField;
    private javax.swing.JComboBox<String> cfdiComboBox;
    private javax.swing.JTextField ciudadTextField;
    private javax.swing.JTextField codigoPostalTextField;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JTextArea datosPedidoTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCFDI;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCodigoPostal;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDatosPedido;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlDatosPedido;
    private javax.swing.JTextField rfcTextField;
    // End of variables declaration//GEN-END:variables

private void inicializarComboBoxes() {
    String[] usoCFDI = {
        "Adquisición de mercancías",
        "Devoluciones, descuentos o bonificaciones",
        "Gastos en general",
        "Construcciones",
        "Equipo de transporte",
        "Equipo de cómputo"
    };
 
    for (String item : usoCFDI) {
        cfdiComboBox.addItem(item);  
    }
}
 
public void setSolicitudControl(ISolicitudFacturaControl control) {
    this.solicitudControl = control;
}
 
public void setSolicitudFactura(SolicitudFacturaDTO solicitud) {
    this.solicitudFacturaDTO = solicitud;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    String datosText = String.format(
        "N° de Pedido: %d\n\n" +
        "Proveedor: \n\n" +
        "Monto: \n\n" +
        "Fecha: %s",
        solicitud.getNumeroOrden(),
        sdf.format(solicitud.getFechaSolicitud())
    );
    
    datosPedidoTextArea.setText(datosText);
}
 
private boolean validarCampos() {
    if (rfcTextField.getText().trim().isEmpty()) {
        marcarCampoError(rfcTextField);
        JOptionPane.showMessageDialog(this, "El RFC es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if (TextFieldrazonSocial.getText().trim().isEmpty()) {
        marcarCampoError(TextFieldrazonSocial);
        JOptionPane.showMessageDialog(this, "La Razón Social es obligatoria", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if (calleTextField.getText().trim().isEmpty()) {
        marcarCampoError(calleTextField);
        JOptionPane.showMessageDialog(this, "La Calle es obligatoria", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if (ciudadTextField.getText().trim().isEmpty()) {
        marcarCampoError(ciudadTextField);
        JOptionPane.showMessageDialog(this, "La Ciudad es obligatoria", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if (codigoPostalTextField.getText().trim().isEmpty()) {
        marcarCampoError(codigoPostalTextField);
        JOptionPane.showMessageDialog(this, "El Código Postal es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if (correoTextField.getText().trim().isEmpty()) {
        marcarCampoError(correoTextField);
        JOptionPane.showMessageDialog(this, "El Correo es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
 
    limpiarErrores();
    return true;
}
 
private void marcarCampoError(javax.swing.JTextField campo) {
    campo.setBackground(new Color(255, 200, 200));
    campo.setForeground(Color.RED);
}
 
private void limpiarErrores() {
    rfcTextField.setBackground(Color.WHITE);
    TextFieldrazonSocial.setBackground(Color.WHITE);
    calleTextField.setBackground(Color.WHITE);
    ciudadTextField.setBackground(Color.WHITE);
    codigoPostalTextField.setBackground(Color.WHITE);
    correoTextField.setBackground(Color.WHITE);
    
    rfcTextField.setForeground(Color.BLACK);
    TextFieldrazonSocial.setForeground(Color.BLACK);
    calleTextField.setForeground(Color.BLACK);
    ciudadTextField.setForeground(Color.BLACK);
    codigoPostalTextField.setForeground(Color.BLACK);
    correoTextField.setForeground(Color.BLACK);
}
 
}
