/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.presentacion_mariscos.SolicitudFactura;

import com.mycompany.controller_mariscos.orden.IOrdenControl;
import com.mycompany.controller_mariscos.solicitudFactura.ISolicitudFacturaControl;
import com.mycompany.dto_mariscos.Orden;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;






/**
 *
 * @author 52644
 */
public class SeleccionOrden extends javax.swing.JPanel {
    private ISolicitudFacturaControl solicitudControl;



    private IOrdenControl ordenControl;
    private List<Orden> ordenesActuales;
    private Orden ordenSeleccionada;

    private JPanel pnlContainer;
    private pnlDatosFacturacion pnlDatos;
    private JLabel lblVentana;

    private int paginaActual = 1;
    private final int REGISTROS_POR_PAGINA = 20;
    /**
     * Creates new form SeleccionOrden
     */
    public SeleccionOrden() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        tablaOrdenesTableScrollPane = new javax.swing.JScrollPane();
        tablaOrdenesTable = new javax.swing.JTable();
        btnSiguientePaginaTabla = new javax.swing.JButton();
        btnAnteriorPaginaTabla = new javax.swing.JButton();
        BtnSeleccionar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        ordenarRecienteAntiguoComboBox = new javax.swing.JComboBox<>();
        lblOrdenarRecienteAntiguo = new javax.swing.JLabel();
        lblPedidosRealizadosPorAno = new javax.swing.JLabel();
        pedidosRealizadosPorAnoComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(772, 1331));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Seleccione un pedido");

        tablaOrdenesTable.setBackground(new java.awt.Color(255, 255, 255));
        tablaOrdenesTable.setForeground(new java.awt.Color(255, 255, 255));
        tablaOrdenesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° Orden", "Proveedor", "Estado", "Fecha Creación", "Estado Facturación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaOrdenesTable.getTableHeader().setReorderingAllowed(false);
        tablaOrdenesTableScrollPane.setViewportView(tablaOrdenesTable);

        btnSiguientePaginaTabla.setBackground(new java.awt.Color(35, 53, 74));
        btnSiguientePaginaTabla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSiguientePaginaTabla.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguientePaginaTabla.setText("Siguiente");
        btnSiguientePaginaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguientePaginaTablaActionPerformed(evt);
            }
        });

        btnAnteriorPaginaTabla.setBackground(new java.awt.Color(35, 53, 74));
        btnAnteriorPaginaTabla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAnteriorPaginaTabla.setForeground(new java.awt.Color(255, 255, 255));
        btnAnteriorPaginaTabla.setText("Anterior");
        btnAnteriorPaginaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorPaginaTablaActionPerformed(evt);
            }
        });

        BtnSeleccionar.setBackground(new java.awt.Color(35, 53, 74));
        BtnSeleccionar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        BtnSeleccionar.setText("Seleccionar >");
        BtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionarActionPerformed(evt);
            }
        });

        BtnRegresar.setBackground(new java.awt.Color(35, 53, 74));
        BtnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegresar.setText("< Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        ordenarRecienteAntiguoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lo mas reciente", "lo mas antiguo" }));
        ordenarRecienteAntiguoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarRecienteAntiguoComboBoxActionPerformed(evt);
            }
        });

        lblOrdenarRecienteAntiguo.setForeground(new java.awt.Color(0, 0, 0));
        lblOrdenarRecienteAntiguo.setText("Ordenar por : ");

        lblPedidosRealizadosPorAno.setForeground(new java.awt.Color(0, 0, 0));
        lblPedidosRealizadosPorAno.setText("¨Pedidos Realizados en : ");

        pedidosRealizadosPorAnoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2026", "2025", "2024", "2023" }));
        pedidosRealizadosPorAnoComboBox.setPreferredSize(new java.awt.Dimension(114, 22));
        pedidosRealizadosPorAnoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosRealizadosPorAnoComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addGap(380, 380, 380))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAnteriorPaginaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSiguientePaginaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(629, 629, 629)))
                                .addComponent(BtnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblOrdenarRecienteAntiguo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordenarRecienteAntiguoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lblPedidosRealizadosPorAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pedidosRealizadosPorAnoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tablaOrdenesTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordenarRecienteAntiguoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrdenarRecienteAntiguo)
                    .addComponent(lblPedidosRealizadosPorAno)
                    .addComponent(pedidosRealizadosPorAnoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaOrdenesTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSiguientePaginaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnteriorPaginaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );

        BtnRegresar.getAccessibleContext().setAccessibleName("Regresar");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionarActionPerformed
    int filaSeleccionada = tablaOrdenesTable.getSelectedRow();

    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una orden", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int indiceReal = ((paginaActual - 1) * REGISTROS_POR_PAGINA) + filaSeleccionada;
    ordenSeleccionada = ordenesActuales.get(indiceReal);

    // Crear DTO con setters
    com.mycompany.dto_mariscos.solicitudFactura.SolicitudFacturaDTO dto =
            new com.mycompany.dto_mariscos.solicitudFactura.SolicitudFacturaDTO();

    dto.setIdPedido(String.valueOf(ordenSeleccionada.getNumeroOrden())); // conversión int → String
    dto.setRazonSocial(ordenSeleccionada.getProveedor());
    dto.setFechaSolicitud(ordenSeleccionada.getFechaCreacion());
    dto.setEstadoFactura(ordenSeleccionada.getEstadoFacturacion());

    pnlDatos.setSolicitudFactura(dto);

    pnlContainer.removeAll();
    pnlContainer.add(pnlDatos, BorderLayout.CENTER);
    lblVentana.setText("Datos de Facturación");
    pnlContainer.revalidate();
    pnlContainer.repaint();
    }//GEN-LAST:event_BtnSeleccionarActionPerformed

    private void ordenarRecienteAntiguoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarRecienteAntiguoComboBoxActionPerformed
        paginaActual = 1;
        cargarOrdenes();
    }//GEN-LAST:event_ordenarRecienteAntiguoComboBoxActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void pedidosRealizadosPorAnoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosRealizadosPorAnoComboBoxActionPerformed
        // TODO add your handling code here:
        paginaActual = 1;
        cargarOrdenes();
    }//GEN-LAST:event_pedidosRealizadosPorAnoComboBoxActionPerformed

    private void btnSiguientePaginaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguientePaginaTablaActionPerformed
  int totalPaginas = (int) Math.ceil((double) ordenesActuales.size() / REGISTROS_POR_PAGINA);
        if (paginaActual < totalPaginas) {
            paginaActual++;
            cargarTabla();
        }
    }//GEN-LAST:event_btnSiguientePaginaTablaActionPerformed

    private void btnAnteriorPaginaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorPaginaTablaActionPerformed
        if (paginaActual > 1) {
            paginaActual--;
            cargarTabla();
        }
    }//GEN-LAST:event_btnAnteriorPaginaTablaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton BtnSeleccionar;
    private javax.swing.JButton btnAnteriorPaginaTabla;
    private javax.swing.JButton btnSiguientePaginaTabla;
    private javax.swing.JLabel lblOrdenarRecienteAntiguo;
    private javax.swing.JLabel lblPedidosRealizadosPorAno;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JComboBox<String> ordenarRecienteAntiguoComboBox;
    private javax.swing.JComboBox<String> pedidosRealizadosPorAnoComboBox;
    private javax.swing.JTable tablaOrdenesTable;
    private javax.swing.JScrollPane tablaOrdenesTableScrollPane;
    // End of variables declaration//GEN-END:variables
/*
    public void setReferences(
            JPanel pnlContainer,
            pnlDatosFacturacion pnlDatos,
            JLabel lblVentana
    ) {
        this.pnlContainer = pnlContainer;
        this.pnlDatos = pnlDatos;
        this.lblVentana = lblVentana;
    }
     */
    public void setSolicitudControl(ISolicitudFacturaControl control) {
        this.solicitudControl = control;
        cargarOrdenes();
    }

 public void setReferences(JPanel pnlContainer, pnlDatosFacturacion pnlDatos, JLabel lblVentana) {
        this.pnlContainer = pnlContainer;
        this.pnlDatos = pnlDatos;
        this.lblVentana = lblVentana;
    }
    public void setOrdenControl(IOrdenControl control) {
        this.ordenControl = control;
        cargarOrdenes();
    }

    private void cargarOrdenes() {
        try {
            int ano = Integer.parseInt((String) pedidosRealizadosPorAnoComboBox.getSelectedItem());
            String ordenamiento = ordenarRecienteAntiguoComboBox.getSelectedIndex() == 0 ? "nuevo" : "antiguo";

            ordenesActuales = ordenControl.obtenerOrdenesPorAno(ano);
            cargarTabla();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar órdenes: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarTabla() {
        DefaultTableModel model = (DefaultTableModel) tablaOrdenesTable.getModel();
        model.setRowCount(0);

        int inicio = (paginaActual - 1) * REGISTROS_POR_PAGINA;
        int fin = Math.min(inicio + REGISTROS_POR_PAGINA, ordenesActuales.size());

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (int i = inicio; i < fin; i++) {
            Orden orden = ordenesActuales.get(i);
            model.addRow(new Object[]{
                orden.getNumeroOrden(),
                orden.getProveedor(),
                orden.getEstado(),
                sdf.format(orden.getFechaCreacion()),
                orden.getEstadoFacturacion()
            });
        }
    }

}
