/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion_mariscos.RecepcionMercancia;

import com.mycompany.controller_marisco.orden.IOrdenControl;
import com.mycompany.controller_marisco.orden.OrdenControl;
import com.mycompany.controller_mariscos.insumo.IInsumoControl;
import com.mycompany.controller_mariscos.insumo.InsumoControl;
import com.mycompany.dto_mariscos.Insumo;
import com.mycompany.dto_mariscos.mermas.InsumoDTO;
import com.mycompany.dto_mariscos.mermas.OrdenDTO;
import com.mycompany.persistencia_mariscos.insumo.InsumoDAO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import org.bson.types.ObjectId;

/**
 *
 * @author joser
 */
public class PnlRecepcionMercancia extends javax.swing.JPanel {

    private final Color COLOR_AZUL_CLARO = new Color(209, 236, 252);
    private final Color COLOR_VERDE_OK = new Color(165, 231, 191);
    private final Color COLOR_ROJO_FAIL = new Color(255, 204, 201);
    private final Color COLOR_BTN_FINALIZAR = new Color(74, 184, 102);

    private JComboBox<OrdenDTO> cbOrdenes;
    private JLabel lblProveedor, lblFecha, lblEstado;
    private JTable tablaDetalles;
    private DefaultTableModel modeloTabla;
    private JPanel pnlListaResumen;
    private OrdenDTO ordenSeleccionada;
    
    private IOrdenControl ordenControl;
    private IInsumoControl insumoControl;

    /**
     * Creates new form PnlRecepcionMercancia
     */
    public PnlRecepcionMercancia() {
        this.insumoControl = new InsumoControl(new InsumoDAO());
        this.ordenControl = new OrdenControl();
        initComponents();
        iniciarComponentes();
        configurarEventos();
        configurarComboBox(); // Configuramos el Renderer
        cargarOrdenesDesdeBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1131, 772));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1131, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarComponentes() {
        setLayout(new GridBagLayout());
        setBackground(Color.WHITE);
        GridBagConstraints gbc = new GridBagConstraints();

        // --- COLUMNA IZQUIERDA (70%) ---
        JPanel pnlIzquierdo = new JPanel(new GridBagLayout());
        pnlIzquierdo.setOpaque(false);
        GridBagConstraints gbcIzq = new GridBagConstraints();
        gbcIzq.fill = GridBagConstraints.BOTH;
        gbcIzq.insets = new Insets(5, 5, 5, 5);

        // 1. Selector y Datos Proveedor
        JPanel pnlHeader = new JPanel(new GridLayout(1, 2, 20, 0));
        pnlHeader.setBackground(COLOR_AZUL_CLARO);
        pnlHeader.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));

        JPanel pnlCombo = new JPanel(new BorderLayout(0, 5));
        pnlCombo.setOpaque(false);
        pnlCombo.add(new JLabel("Seleccionar orden de compra:"), BorderLayout.NORTH);
        cbOrdenes = new JComboBox<>();
        pnlCombo.add(cbOrdenes, BorderLayout.CENTER);

        JPanel pnlInfoProv = new JPanel(new GridLayout(3, 1));
        pnlInfoProv.setOpaque(false);
        lblProveedor = new JLabel("Proveedor: -");
        lblFecha = new JLabel("Fecha: -");
        lblEstado = new JLabel("Estado: -");
        pnlInfoProv.add(lblProveedor);
        pnlInfoProv.add(lblFecha);
        pnlInfoProv.add(lblEstado);

        pnlHeader.add(pnlCombo);
        pnlHeader.add(pnlInfoProv);
        gbcIzq.gridy = 0;
        gbcIzq.weightx = 1;
        gbcIzq.weighty = 0.15;
        pnlIzquierdo.add(pnlHeader, gbcIzq);

        // 2. Tabla
        modeloTabla = new DefaultTableModel(
                new Object[]{"Ítem", "Pedida", "Recibida", "Unidad", "Validación", "Aprobar"}, 0
        ) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return c == 2 || c == 4 || c == 5; // Recibida, Botón y Checkbox
            }

            @Override
            public Class<?> getColumnClass(int c) {
                if (c == 5) {
                    return Boolean.class;
                }
                return Object.class;
            }
        };
        tablaDetalles = new JTable(modeloTabla);
        tablaDetalles.setRowHeight(45);
        personalizarTabla();

        JScrollPane scroll = new JScrollPane(tablaDetalles);
        scroll.setBorder(BorderFactory.createTitledBorder("Detalles de orden a recibir"));
        gbcIzq.gridy = 1;
        gbcIzq.weighty = 0.7;
        pnlIzquierdo.add(scroll, gbcIzq);

        // 3. Notas
        JTextArea txtNotas = new JTextArea(3, 20);
        JScrollPane scrollNotas = new JScrollPane(txtNotas);
        scrollNotas.setBorder(BorderFactory.createTitledBorder("Notas de recepción"));
        gbcIzq.gridy = 2;
        gbcIzq.weighty = 0.15;
        pnlIzquierdo.add(scrollNotas, gbcIzq);

        // --- COLUMNA DERECHA (Resumen) ---
        JPanel pnlDerecho = crearPanelDerecho();

        // Agregar al principal
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weighty = 1.0;
        gbc.gridx = 0;
        gbc.weightx = 0.7;
        add(pnlIzquierdo, gbc);
        gbc.gridx = 1;
        gbc.weightx = 0.3;
        add(pnlDerecho, gbc);
    }

    private JPanel crearPanelDerecho() {
        JPanel pnl = new JPanel(new BorderLayout());
        pnl.setBackground(Color.WHITE);
        pnl.setBorder(BorderFactory.createMatteBorder(0, 1, 0, 0, Color.LIGHT_GRAY));

        JLabel titulo = new JLabel("Resumen de recepción", SwingConstants.CENTER);
        titulo.setFont(new Font("SansSerif", Font.BOLD, 18));
        titulo.setBorder(BorderFactory.createEmptyBorder(20, 0, 20, 0));
        pnl.add(titulo, BorderLayout.NORTH);

        pnlListaResumen = new JPanel();
        pnlListaResumen.setLayout(new BoxLayout(pnlListaResumen, BoxLayout.Y_AXIS));
        pnlListaResumen.setBackground(Color.WHITE);
        pnl.add(new JScrollPane(pnlListaResumen), BorderLayout.CENTER);

        JPanel pnlFooter = new JPanel(new GridLayout(4, 1, 0, 5));
        pnlFooter.setBackground(Color.WHITE);
        pnlFooter.setBorder(BorderFactory.createEmptyBorder(10, 20, 20, 20));



        JButton btnFinalizar = new JButton("Finalizar recepción y actualizar stock");
        btnFinalizar.setBackground(COLOR_BTN_FINALIZAR);
        btnFinalizar.setForeground(Color.WHITE);
        btnFinalizar.setFocusPainted(false);


        pnlFooter.add(btnFinalizar);
        pnl.add(pnlFooter, BorderLayout.SOUTH);

        return pnl;
    }

    private void personalizarTabla() {
        TableColumnModel columnModel = tablaDetalles.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(200); // Ítem
        columnModel.getColumn(1).setPreferredWidth(80);  // Pedida
        columnModel.getColumn(2).setPreferredWidth(80);  // Recibida
        columnModel.getColumn(3).setPreferredWidth(80);  // Unidad
        columnModel.getColumn(4).setPreferredWidth(120); // Validación (Botón)
        columnModel.getColumn(5).setPreferredWidth(80);  // Aprobar (Checkbox)

        // Configurar el Renderer y Editor del botón en la columna 4
        columnModel.getColumn(4).setCellRenderer(new BotonEstadoRenderer());
        columnModel.getColumn(4).setCellEditor(new BotonEstadoEditor(new JCheckBox()));
    }

    private void configurarEventos() {
        // Evento Combo Box
        cbOrdenes.addActionListener(e -> {
            OrdenDTO seleccionada = (OrdenDTO) cbOrdenes.getSelectedItem();
            if (seleccionada != null) {
                System.out.println("Orden seleccionada: " + seleccionada.getNumeroOrden());
                cargarDatosReales(seleccionada);
            }
        });

        // Evento de cambio en la tabla (para el Checkbox y Cantidad)
        modeloTabla.addTableModelListener(e -> {
            if (e.getColumn() == 5 || e.getColumn() == 2) {
                actualizarResumen();
            }
        });
    }

    
    private void cargarDatosReales(OrdenDTO orden) {
        modeloTabla.setRowCount(0); // Limpiar tabla


        lblProveedor.setText("Proveedor: " + orden.getProveedor());

        if (orden.getFechaCreacion() != null) {
            lblFecha.setText("Fecha de pedido: " + orden.getFechaCreacion().toString());
        } else {
            lblFecha.setText("Fecha de pedido: No disponible");
        }
        
        lblEstado.setText("Estado: " + orden.getEstado());
        
        orden.getItems().forEach((idInsumo, cantidadPedida) -> {
            System.out.println("Buscando insumo con ID: " + idInsumo);
            try {
                // Buscamos los detalles del insumo para mostrar Nombre y Unidad
                Insumo insumo = insumoControl.obtenerInsumoPorId(new ObjectId(idInsumo));

                modeloTabla.addRow(new Object[]{
                    insumo.getNombre(), // Nombre real del insumo
                    cantidadPedida, // Cantidad desde la Orden
                    0, // Cantidad Recibida inicial
                    insumo.getUnidadMedida(), // Unidad (KG, PZ, etc)
                    "Buen estado",
                    false 
                });
            } catch (Exception e) {
                System.err.println("Error al cargar item de insumo: " + e.getMessage());
            }
        });
        
        modeloTabla.fireTableDataChanged();
        tablaDetalles.revalidate();
        tablaDetalles.repaint();
    }
    
    
//    private void cargarDatosSimulados(String oc) {
//        limpiarTodo();
//        lblProveedor.setText("Proveedor: Mariscos del Yaqui");
//        lblFecha.setText("Fecha: 15/02/2026");
//        lblEstado.setText("Estado: Pendiente");
//        
//        try{
//            List<OrdenDTO> listaOrdenesActivas = ordenControl.listarOrdenes();
//            for (OrdenDTO orden: listaOrdenesActivas) {
//                
//            }
//            
//            
//            
//            
//        }
//        catch(Exception ex){
//            System.out.println("error: " + ex.getMessage());
//        }
//        
//        
//        // Simulamos datos de persistencia: {Nombre, CantPedida, CantRecibida, Unidad, Estado, Check, PrecioUnitario}
//        modeloTabla.addRow(new Object[]{"Filete de pescado", 30, 30, "KG", "Buen estado", false, 25.20});
//        modeloTabla.addRow(new Object[]{"Tomate fresco", 25, 0, "KG", "Buen estado", false, 8.00});
//        modeloTabla.addRow(new Object[]{"Sal de grano", 5, 5, "KG", "Buen estado", false, 40.00});
//    }

    private void actualizarResumen() {
        pnlListaResumen.removeAll();
        int contadorItems = 0;

        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            boolean aprobado = (boolean) modeloTabla.getValueAt(i, 5);
            if (aprobado) {
                String nombre = (String) modeloTabla.getValueAt(i, 0);
                String cantRecibida = modeloTabla.getValueAt(i, 2).toString();
                String unidad = modeloTabla.getValueAt(i, 3).toString();

                // Solo mostramos información de cantidad y nombre
                JLabel lblItem = new JLabel("• " + nombre + " (" + cantRecibida + " " + unidad + ")");
                lblItem.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
                pnlListaResumen.add(lblItem);
                contadorItems++;
            }
        }

        // Opcional: Un label que indique cuántos productos se están aprobando
        // lblConteoItems.setText("Productos a recibir: " + contadorItems);
        pnlListaResumen.revalidate();
        pnlListaResumen.repaint();
    }

    private void limpiarTodo() {
        modeloTabla.setRowCount(0);
        pnlListaResumen.removeAll();
        lblProveedor.setText("Proveedor: -");
        pnlListaResumen.revalidate();
        pnlListaResumen.repaint();
    }

    private void configurarComboBox() {
        Object seleccionado = cbOrdenes.getSelectedItem();

        if (seleccionado instanceof OrdenDTO) {
            OrdenDTO orden = (OrdenDTO) seleccionado;
            // Llamas a tu método de llenado de tabla pasando el DTO real
            this.llenarTablaConOrden(orden);

            // Actualizar los labels superiores
            lblProveedor.setText("Proveedor: " + orden.getProveedor());
            lblFecha.setText("Fecha de pedido: " + orden.getFechaCreacion().toString());
            lblEstado.setText("Estado: " + orden.getEstado());
        } else {
            limpiarTodo();
        }
    }

    private void llenarTablaConOrden(OrdenDTO orden) {
        modeloTabla.setRowCount(0);

        orden.getItems().forEach((idInsumo, cantidadPedida) -> {
            try {
                Insumo insumo = insumoControl.obtenerInsumoPorId(new ObjectId(idInsumo));
                if (insumo != null) {
                    modeloTabla.addRow(new Object[]{
                        insumo.getNombre(),
                        cantidadPedida,
                        cantidadPedida,
                        insumo.getUnidadMedida(),
                        "Buen estado",
                        false
                    });
                }
            } catch (Exception ex) {
                System.err.println("Error al cargar insumo: " + idInsumo);
            }
        });
    }

    private void cargarOrdenesDesdeBD() {
        try {
            List<OrdenDTO> lista = ordenControl.listarOrdenes();
            cbOrdenes.removeAllItems();

            for (OrdenDTO orden : lista) {
                if (orden.getEstado().equalsIgnoreCase("Pendiente")
                        || orden.getEstado().equalsIgnoreCase("Confirmada")) {
                    cbOrdenes.addItem(orden);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar órdenes: " + e.getMessage());
        }
    }

    // --- CLASES PARA EL BOTÓN DINÁMICO EN LA TABLA ---
    class BotonEstadoRenderer extends JButton implements TableCellRenderer {

        public BotonEstadoRenderer() {
            setOpaque(true);
            setBorder(BorderFactory.createLineBorder(Color.WHITE, 1));
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            String texto = (value != null) ? value.toString() : "Buen estado";
            setText(texto);

            if (texto.equalsIgnoreCase("Buen estado")) {
                setBackground(COLOR_VERDE_OK);
            } else {
                setBackground(COLOR_ROJO_FAIL);
            }
            return this;
        }
    }

    class BotonEstadoEditor extends DefaultCellEditor {
    private JButton btn;
    private String label;

        public BotonEstadoEditor(JCheckBox checkBox) {
            super(checkBox);
            btn = new JButton();
            btn.setOpaque(true);
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // 1. Cambiamos el estado lógicamente
                    label = label.equals("Buen estado") ? "Mal estado" : "Buen estado";

                    // 2. Actualizamos el aspecto visual del botón del editor inmediatamente
                    btn.setText(label);
                    btn.setBackground(label.equals("Buen estado") ? COLOR_VERDE_OK : COLOR_ROJO_FAIL);

                    // 3. Importante: Detenemos la edición para que el JTable guarde el nuevo String en el modelo
                    fireEditingStopped();
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            // Al iniciar el clic, recuperamos el valor actual de la celda
            label = (value != null) ? value.toString() : "Buen estado";
            btn.setText(label);
            btn.setBackground(label.equals("Buen estado") ? COLOR_VERDE_OK : COLOR_ROJO_FAIL);
            return btn;
        }

        @Override
        public Object getCellEditorValue() {
            return label; // Este es el valor que se guardará en el TableModel
        }

        @Override
        public boolean stopCellEditing() {
            return super.stopCellEditing();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
