/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.presentacion_mariscos.CarritoInsumos;

import com.mycompany.presentacion_mariscos.SeleccionProveedor.PnlProveedores;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import com.mycompany.dto_mariscos.Carrito;
import com.mycompany.dto_mariscos.Insumo;
import com.mycompany.dto_mariscos.Inventario;


/**
 *
 * @author demib
 */
public class PnlCarrito extends javax.swing.JPanel {
    
    private List<ItemCarrito> listaOrden;
    private Carrito carritoEntidad;
    
    //necesario para desplegar PnlProveedores2
    private JPanel pnlContainer;
    private PnlProveedores pnlProveedores2;
    private JLabel lblVentana;

    /**
     * Creates new form PnlCarrito
     */
    public PnlCarrito() {
        initComponents();
        listaOrden = new ArrayList<>();
        carritoEntidad = new Carrito();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCardsCarrito = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 53, 74), 2));

        pnlHeader.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Carrito");
        jLabel1.setAlignmentY(0.0F);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlCardsCarrito.setBackground(new java.awt.Color(250, 250, 250));
        pnlCardsCarrito.setLayout(new javax.swing.BoxLayout(pnlCardsCarrito, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlCardsCarrito);

        btnSiguiente.setBackground(new java.awt.Color(35, 53, 74));
        btnSiguiente.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // Despliega panel proveedores
        pnlContainer.removeAll();
        pnlContainer.add(pnlProveedores2, BorderLayout.CENTER);
         lblVentana.setText("Selecciona Proveedor");
        pnlContainer.revalidate();
        pnlContainer.repaint();
        
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCardsCarrito;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables

    
        //necesario para desplegar PnlProveedores
    public void setReferences(JPanel pnlContainer, PnlProveedores pnlProveedores2, JLabel lblVentana) {
        this.pnlContainer = pnlContainer;
        this.pnlProveedores2 = pnlProveedores2;
         this.lblVentana = lblVentana;
    }
    
    public JButton getjButton1() {
        return btnSiguiente;
    }

    public void setjButton1(JButton jButton1) {
        this.btnSiguiente = jButton1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JPanel getPnlCardsCarrito() {
        return pnlCardsCarrito;
    }

    public void setPnlCardsCarrito(JPanel pnlCardsCarrito) {
        this.pnlCardsCarrito = pnlCardsCarrito;
    }

    public JPanel getPnlHeader() {
        return pnlHeader;
    }

    public void setPnlHeader(JPanel pnlHeader) {
        this.pnlHeader = pnlHeader;
    }

    public List<ItemCarrito> getListaOrden() {
        return listaOrden;
    }

    public void setListaOrden(List<ItemCarrito> listaOrden) {
        this.listaOrden = listaOrden;
    }
    
    public Carrito getCarritoEntidad() {
        return carritoEntidad;
    }
    
    public void agregarItemAlCarrito(Inventario inventario, double cantidad) {
        ItemCarrito item = new ItemCarrito(inventario, cantidad, this);
        item.getLblCantidad().setText(cantidad + " " + inventario.getInsumo().getUnidadMedida());
        listaOrden.add(item);
        pnlCardsCarrito.add(item);
        
        carritoEntidad.agregarInsumo(inventario.getInsumo(), cantidad);
        
        revalidate();
        repaint();
    }
    
    public void eliminarItem(ItemCarrito item, Insumo insumo) {
        listaOrden.remove(item);
        pnlCardsCarrito.remove(item);
        carritoEntidad.quitarInsumo(insumo);
        revalidate();
        repaint();
    }
    
    public void actualizarCantidadItem(Insumo insumo, double nuevaCantidad) {
        carritoEntidad.actualizarCantidad(insumo, nuevaCantidad);
        // La vista ya se actualiza en ItemCarrito, no necesitamos más
    }

    @Override
    public String toString() {
        return "PnlCarrito{" + "listaOrden=" + listaOrden + ", btnSiguiente=" + btnSiguiente + ", jLabel1=" + jLabel1 + ", jScrollPane1=" + jScrollPane1 + ", pnlCardsCarrito=" + pnlCardsCarrito + ", pnlHeader=" + pnlHeader + '}';
    }
    
    

    
}
