/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


package com.mycompany.presentacion_mariscos.CarritoInsumos;

import com.mycompany.controller_mariscos.inventario.IInventarioControl;
import com.mycompany.dto_mariscos.Insumo;
import com.mycompany.dto_mariscos.Inventario;
import com.mycompany.exception_mariscos.DaoException;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author demib
 */
public class PnlProductos extends javax.swing.JPanel {

    private PnlCarrito pnlCarrito;
    
    private IInventarioControl inventarioControl;

    

    private List<Inventario> listaInventario;

    /**
     * Creates new form PnlProductos
     *
     * @param pnlCarrito
     */
    public PnlProductos(PnlCarrito pnlCarrito, IInventarioControl inventarioControl) {
        this.pnlCarrito = pnlCarrito;
        this.inventarioControl = inventarioControl;
        
        listaInventario = new ArrayList<>();

        cargarInventario();

        initComponents();
        generarCardsInsumos();
        
        barraBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtrarCards(barraBusqueda.getText());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();
        lblSeleccioneInsumos = new javax.swing.JLabel();
        barraBusqueda = new javax.swing.JTextField();
        lblBusqueNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCards = new javax.swing.JPanel();

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));

        lblSeleccioneInsumos.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblSeleccioneInsumos.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccioneInsumos.setText("Seleccione los Insumos");

        barraBusqueda.setBackground(new java.awt.Color(250, 250, 250));
        barraBusqueda.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        barraBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        barraBusqueda.setPreferredSize(null);

        lblBusqueNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblBusqueNombre.setText("Busque por: Nombre");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 772));

        pnlCards.setLayout(new java.awt.GridLayout(0, 3, 20, 20));
        jScrollPane1.setViewportView(pnlCards);

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addComponent(lblSeleccioneInsumos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblBusqueNombre)))
                .addContainerGap())
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccioneInsumos)
                    .addComponent(barraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBusqueNombre)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusqueNombre;
    private javax.swing.JLabel lblSeleccioneInsumos;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables

    private void generarCardsInsumos() {
        filtrarCards("");
        for (Inventario inventario : listaInventario) {
            CardInsumos card = new CardInsumos(inventario);

            card.getBtnAgregar().addActionListener(e -> {
                Double cantidad = Double.valueOf(card.getTxtCantidad().getText());

                // verificar si el insumo ya esta en la lista
                boolean yaExiste = pnlCarrito.getListaOrden().stream()
                        .anyMatch(i -> i.getInventario().getInsumo().getNombre()
                        .equals(inventario.getInsumo().getNombre()));

                if (yaExiste) {
                    System.out.println("El insumo ya esta en el carrito");
                    return; // no agrega duplicado
                }
                
                

                
                
                    pnlCarrito.agregarItemAlCarrito(inventario, cantidad);
                
                
                card.getTxtCantidad().setText("0");
                System.out.println("Items en carrito: " + pnlCarrito.getListaOrden().size());
            });

            pnlCards.add(card);
        }

        pnlCards.revalidate();
        pnlCards.repaint();

    }
    
    private void cargarInventario(){
        try{
            listaInventario = inventarioControl.obtenerTodos();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al cargar inventario: " + e);
            
        }
    }
    
    private void filtrarCards(String textoBusqueda) {
        pnlCards.removeAll(); // limpia los cards actuales

        List<Inventario> filtrados;

        if (textoBusqueda == null || textoBusqueda.isBlank()) {
            filtrados = listaInventario; // muestra todos
        } else {
            // filtra por nombre ignorando mayusculas
            filtrados = listaInventario.stream()
                .filter(inv -> inv.getInsumo().getNombre()
                    .toLowerCase()
                    .contains(textoBusqueda.toLowerCase()))
                .collect(java.util.stream.Collectors.toList());
        }

        // regenera los cards con la lista filtrada
        for (Inventario inventario : filtrados) {
            CardInsumos card = new CardInsumos(inventario);

            card.getBtnAgregar().addActionListener(e -> {
                Double cantidad = Double.valueOf(card.getTxtCantidad().getText());

                boolean yaExiste = pnlCarrito.getListaOrden().stream()
                    .anyMatch(i -> i.getInventario().getInsumo().getNombre()
                        .equals(inventario.getInsumo().getNombre()));

                if (yaExiste) {
                    System.out.println("El insumo ya esta en el carrito");
                    return;
                }

                pnlCarrito.agregarItemAlCarrito(inventario, cantidad);
                card.getTxtCantidad().setText("0");
            });

            pnlCards.add(card);
        }

        pnlCards.revalidate();
        pnlCards.repaint();
    }



    
    
//    private void cargarInsumosMock(){
//        listaInsumos.add(new Insumo("Camarón", "kg", "Mariscos"));
//        listaInsumos.add(new Insumo("Pulpo", "kg", "Mariscos"));
//        listaInsumos.add(new Insumo("Filete de pescado", "kg", "Pescados"));
//        listaInsumos.add(new Insumo("Ostión", "pieza", "Mariscos"));
//        listaInsumos.add(new Insumo("Limón", "kg", "Verduras"));
//        listaInsumos.add(new Insumo("Cebolla morada", "kg", "Verduras"));
//        listaInsumos.add(new Insumo("Chile serrano", "kg", "Verduras"));
//        listaInsumos.add(new Insumo("Aguacate", "pieza", "Verduras"));
//        listaInsumos.add(new Insumo("Salsa inglesa", "botella", "Condimentos"));
//        listaInsumos.add(new Insumo("Catsup", "botella", "Condimentos"));
//        listaInsumos.add(new Insumo("Tostadas", "paquete", "Acompañamientos"));
//        listaInsumos.add(new Insumo("Refresco", "botella", "Bebidas"));
//    }
//
//    
//    private void cargarInventarioMock(){
//        listaInventario.add(new Inventario(listaInsumos.get(0), 20.0, 4.0));   // Camarón
//        listaInventario.add(new Inventario(listaInsumos.get(1), 10.0, 6.0));    // Pulpo
//        listaInventario.add(new Inventario(listaInsumos.get(2), 18.0, 12.5));   // Filete de pescado
//        listaInventario.add(new Inventario(listaInsumos.get(3), 100.0, 65.0)); // Ostión
//        listaInventario.add(new Inventario(listaInsumos.get(4), 25.0, 8.0));    // Limón
//        listaInventario.add(new Inventario(listaInsumos.get(5), 15.0, 7.5));    // Cebolla morada
//        listaInventario.add(new Inventario(listaInsumos.get(6), 8.0, 3.0));     // Chile serrano
//        listaInventario.add(new Inventario(listaInsumos.get(7), 30.0, 12.0));   // Aguacate
//        listaInventario.add(new Inventario(listaInsumos.get(8), 12.0, 5.0));    // Salsa inglesa
//        listaInventario.add(new Inventario(listaInsumos.get(9), 10.0, 4.0));    // Catsup
//        listaInventario.add(new Inventario(listaInsumos.get(10), 40.0, 18.0)); // Tostadas
//        listaInventario.add(new Inventario(listaInsumos.get(11), 24.0, 9.0));   // Refresco
//    }

}
