
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presentacion_mariscos;


import com.mycompany.config_mariscos.MongoClientProvider;
import com.mycompany.controller_mariscos.insumo.IInsumoControl;
import com.mycompany.controller_mariscos.insumo.InsumoControl;
import com.mycompany.controller_mariscos.inventario.IInventarioControl;
import com.mycompany.controller_mariscos.inventario.InventarioControl;
import com.mycompany.persistencia_mariscos.insumo.IInsumoDAO;
import com.mycompany.persistencia_mariscos.insumo.InsumoDAO;
import com.mycompany.persistencia_mariscos.inventario.IInventarioDAO;
import com.mycompany.persistencia_mariscos.inventario.InventarioDAO;
import com.mycompany.presentacion_mariscos.CarritoInsumos.PnlProductos;
import com.mycompany.presentacion_mariscos.CarritoInsumos.PnlCarrito;
import com.mycompany.presentacion_mariscos.SeleccionProveedor.PnlProveedores;
import java.awt.BorderLayout;

/**
 *
 * @author demib
 */
public class MainFrame extends javax.swing.JFrame {
    
        /* moviendo por pruebas
    PnlCarrito pnlCarrito = new PnlCarrito();
    PnlProductos pnlProductos = new PnlProductos(pnlCarrito);
    */
    
    
    
    //---DAOS---
    private IInsumoDAO insumoDAO;
    private IInventarioDAO inventarioDAO;
    
    
    //---CONTROLLERS---
    private IInsumoControl insumoControl;
    private IInventarioControl inventarioControl;
    
    private PnlCarrito pnlCarrito;
    private PnlProductos pnlProductos;
    private PnlProveedores pnlProveedores2;
    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        MongoClientProvider.INSTANCE.init();
        
        insumoDAO = new InsumoDAO();
        inventarioDAO = new InventarioDAO();


        //---CONTROLLERS---
        insumoControl = new InsumoControl(insumoDAO);
        inventarioControl = new InventarioControl(inventarioDAO);
        
        initComponents();
        
                
        pnlCarrito = new PnlCarrito();
        pnlProductos = new PnlProductos(pnlCarrito, inventarioControl);
        pnlProveedores2 = new PnlProveedores();
        
         pnlCarrito.setReferences(pnlContainer, pnlProveedores2,lblVentana);
         
          pnlProveedores2.setReferences(pnlContainer, pnlProductos, pnlCarrito, lblVentana);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblNombreSistema = new javax.swing.JLabel();
        lblVentana = new javax.swing.JLabel();
        pnlNavbar = new javax.swing.JPanel();
        lblInventario = new javax.swing.JLabel();
        btnMermas = new javax.swing.JLabel();
        btnRegInsumosAlCorte = new javax.swing.JTextArea();
        lblCompras = new javax.swing.JLabel();
        btnGenerarOrdenCompra = new javax.swing.JLabel();
        btnRecepcionMercancia = new javax.swing.JTextArea();
        lblPagosYFacturacion = new javax.swing.JTextArea();
        btnPagosPendientes = new javax.swing.JLabel();
        btnFacturacionOrdenCompra = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnlHeader.setBackground(new java.awt.Color(194, 232, 255));

        lblNombreSistema.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblNombreSistema.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreSistema.setText("SIGINV");

        lblVentana.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        lblVentana.setForeground(new java.awt.Color(0, 0, 0));
        lblVentana.setText("Menu Principal");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblNombreSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 938, Short.MAX_VALUE)
                .addComponent(lblVentana)
                .addGap(31, 31, 31))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreSistema)
                    .addComponent(lblVentana))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNavbar.setBackground(new java.awt.Color(35, 53, 74));

        lblInventario.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        lblInventario.setForeground(new java.awt.Color(255, 255, 255));
        lblInventario.setText("Inventario");

        btnMermas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnMermas.setForeground(new java.awt.Color(255, 255, 255));
        btnMermas.setText("Mermas");

        btnRegInsumosAlCorte.setEditable(false);
        btnRegInsumosAlCorte.setBackground(new java.awt.Color(35, 53, 74));
        btnRegInsumosAlCorte.setColumns(2);
        btnRegInsumosAlCorte.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnRegInsumosAlCorte.setForeground(new java.awt.Color(255, 255, 255));
        btnRegInsumosAlCorte.setRows(5);
        btnRegInsumosAlCorte.setText("Registrar Insumos al\nCorte del dia");
        btnRegInsumosAlCorte.setToolTipText("");
        btnRegInsumosAlCorte.setBorder(null);
        btnRegInsumosAlCorte.setFocusable(false);

        lblCompras.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        lblCompras.setForeground(new java.awt.Color(255, 255, 255));
        lblCompras.setText("Compras");

        btnGenerarOrdenCompra.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnGenerarOrdenCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarOrdenCompra.setText("Generar orden de compra");
        btnGenerarOrdenCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarOrdenCompraMouseClicked(evt);
            }
        });

        btnRecepcionMercancia.setEditable(false);
        btnRecepcionMercancia.setBackground(new java.awt.Color(35, 53, 74));
        btnRecepcionMercancia.setColumns(2);
        btnRecepcionMercancia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnRecepcionMercancia.setForeground(new java.awt.Color(255, 255, 255));
        btnRecepcionMercancia.setRows(5);
        btnRecepcionMercancia.setText("Recepcion de Mercancia");
        btnRecepcionMercancia.setToolTipText("");
        btnRecepcionMercancia.setBorder(null);
        btnRecepcionMercancia.setFocusable(false);

        lblPagosYFacturacion.setEditable(false);
        lblPagosYFacturacion.setBackground(new java.awt.Color(35, 53, 74));
        lblPagosYFacturacion.setColumns(2);
        lblPagosYFacturacion.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        lblPagosYFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        lblPagosYFacturacion.setRows(5);
        lblPagosYFacturacion.setText("Pagos y\nFacturacion");
        lblPagosYFacturacion.setToolTipText("");
        lblPagosYFacturacion.setBorder(null);
        lblPagosYFacturacion.setFocusable(false);

        btnPagosPendientes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnPagosPendientes.setForeground(new java.awt.Color(255, 255, 255));
        btnPagosPendientes.setText("Pagos pendientes");

        btnFacturacionOrdenCompra.setEditable(false);
        btnFacturacionOrdenCompra.setBackground(new java.awt.Color(35, 53, 74));
        btnFacturacionOrdenCompra.setColumns(2);
        btnFacturacionOrdenCompra.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnFacturacionOrdenCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturacionOrdenCompra.setRows(5);
        btnFacturacionOrdenCompra.setText("Facturacion de la Orden de compra");
        btnFacturacionOrdenCompra.setToolTipText("");
        btnFacturacionOrdenCompra.setBorder(null);
        btnFacturacionOrdenCompra.setFocusable(false);

        btnSalir.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");

        javax.swing.GroupLayout pnlNavbarLayout = new javax.swing.GroupLayout(pnlNavbar);
        pnlNavbar.setLayout(pnlNavbarLayout);
        pnlNavbarLayout.setHorizontalGroup(
            pnlNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInventario)
                    .addComponent(btnMermas)
                    .addComponent(btnRegInsumosAlCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompras)
                    .addComponent(btnGenerarOrdenCompra)
                    .addComponent(btnRecepcionMercancia, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagosYFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagosPendientes)
                    .addComponent(btnFacturacionOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlNavbarLayout.setVerticalGroup(
            pnlNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavbarLayout.createSequentialGroup()
                .addComponent(lblInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMermas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegInsumosAlCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarOrdenCompra)
                .addGap(12, 12, 12)
                .addComponent(btnRecepcionMercancia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPagosYFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagosPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFacturacionOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainer.setPreferredSize(null);
        pnlContainer.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNavbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNavbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarOrdenCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarOrdenCompraMouseClicked
        // TODO add your handling code here:
        pnlContainer.removeAll();
        pnlContainer.add(pnlProductos, BorderLayout.CENTER);
        pnlContainer.add(pnlCarrito, BorderLayout.EAST);
        lblVentana.setText("Generar Orden De Compra");
        pnlContainer.revalidate();
        pnlContainer.repaint();
        
        
    }//GEN-LAST:event_btnGenerarOrdenCompraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea btnFacturacionOrdenCompra;
    private javax.swing.JLabel btnGenerarOrdenCompra;
    private javax.swing.JLabel btnMermas;
    private javax.swing.JLabel btnPagosPendientes;
    private javax.swing.JTextArea btnRecepcionMercancia;
    private javax.swing.JTextArea btnRegInsumosAlCorte;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel lblCompras;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblNombreSistema;
    private javax.swing.JTextArea lblPagosYFacturacion;
    private javax.swing.JLabel lblVentana;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlNavbar;
    // End of variables declaration//GEN-END:variables
}
